// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow_API.Data;

#nullable disable

namespace TaskFlow_API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20261002011829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow_API.Models.Proyecto", b =>
                {
                    b.Property<int>("Id_proyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_proyecto"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id_proyecto");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("TaskFlow_API.Models.Tarea", b =>
                {
                    b.Property<int>("Id_tarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_tarea"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_tarea");

                    b.HasIndex("Id_Proyecto");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("tareas", t =>
                        {
                            t.HasCheckConstraint("CH_TAREA_ESTADO", "[Estado] IN ('Pendiente', 'En proceso', 'Finalizado')");

                            t.HasCheckConstraint("CH_TAREA_PRIORIDAD", "[Prioridad] IN ('Baja', 'Media', 'Alta')");
                        });
                });

            modelBuilder.Entity("TaskFlow_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_usuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", t =>
                        {
                            t.HasCheckConstraint("CH_USUARIO_ROL", "[Rol] IN ('Administrador', 'Usuario')");
                        });
                });

            modelBuilder.Entity("TaskFlow_API.Models.Proyecto", b =>
                {
                    b.HasOne("TaskFlow_API.Models.Usuario", "usuario")
                        .WithMany("proyecto")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TaskFlow_API.Models.Tarea", b =>
                {
                    b.HasOne("TaskFlow_API.Models.Proyecto", "proyecto")
                        .WithMany("tarea")
                        .HasForeignKey("Id_Proyecto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaskFlow_API.Models.Usuario", "usuario")
                        .WithMany("tarea")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("proyecto");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TaskFlow_API.Models.Proyecto", b =>
                {
                    b.Navigation("tarea");
                });

            modelBuilder.Entity("TaskFlow_API.Models.Usuario", b =>
                {
                    b.Navigation("proyecto");

                    b.Navigation("tarea");
                });
#pragma warning restore 612, 618
        }
    }
}
